import { Lato, Open_Sans } from 'next/font/google';
import '@/styles/styles.sass';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const lato = Lato({
	subsets: ['latin'],
	weight: ['400', '700', '900'],
	variable: '--font-lato',
});
const openSans = Open_Sans({
	subsets: ['latin'],
	variable: '--font-open-sans',
});

export const metadata = {
	title: 'Blog Strapi and NextJS',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
	return (
		<html lang='en'>
			<body
				className={`${openSans.className} ${lato.variable} ${openSans.variable}`}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
};

export default RootLayout;
